# Azure DevOps pipeline for a simple "Hello World" GitHub repository

trigger:
- main

pool:
  name: 'Default'

stages:
# Build Stage
- stage: Build
  displayName: "Build Stage"
  jobs:
  - job: BuildJob
    displayName: "Build Job"
    steps:
    - script: |
        echo "This is the Build stage"
        echo "Building the project..."
      displayName: "Echo Build Stage"

# Test Stage
- stage: Test
  displayName: "Test Stage"
  dependsOn: Build
  jobs:
  - job: TestJob
    displayName: "Test Job"
    steps:
    - script: |
        echo "This is the Test stage"
        echo "Running tests..."
      displayName: "Echo Test Stage"

# Deploy Stage
- stage: Deploy
  displayName: "Deploy Stage"
  dependsOn: Test
  jobs:
  - job: DeployJob
    displayName: "Deploy Job"
    steps:
    - script: |
        echo "This is the Deploy stage"
        echo "Deploying the application..."
      displayName: "Echo Deploy Stage"
